### ISSUE TITLE
how is orbitcontrols updated

### ISSUE THREAD

**Issue by HasanTheSyrian** [kekkorider/threejs-starter#13]
I'm having issues with getting the template to work with my set-up but OrbitControls don't work. How is it updated exactly?

Expected something along the lines of `controls.update()`.

**Comment by kekkorider** [comment]
What do you mean with this? 🤔

> OrbitControls don't work

Also

> Expected something along the lines of `controls.update()`.

The `update()` method is supposed to be called after any manual changes to the camera's transform, or in the update loop if the `autoRotate` or `enableDamping` properties are enabled, which is not the case in my starter.

Maybe you missed [this part](https://threejs.org/docs/?q=orbitcontrols#examples/en/controls/OrbitControls.update) in the doc? 🙂
